### ISSUE TITLE
Add a variable to lock down RHEL version

### ISSUE THREAD

**Issue by EdwardJ1n** [redhat-sap/sap-rhsm#17]
The repo can be enabled, but can't download repomd.xml due to systems being updated to RHEL 8.3. 
We should add a variable to lock down RHEL version. 

TASK [redhat_sap.sap_hana_mediacheck : install NFS packages for mounting] ***************************************************************************************************
Tuesday 17 November 2020  11:08:39 +0000 (0:00:00.171)       0:01:57.669 ****** 
fatal: [saphana01]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'rhel-8-for-x86_64-sap-netweaver-e4s-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
fatal: [saphana02]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'rhel-8-for-x86_64-sap-netweaver-e4s-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}

**Comment by makentenza** [comment]
It does exist already @EdwardJ1n 

https://github.com/redhat-sap/sap-rhsm/blob/master/tasks/manage-subs.yml#L50-L53

**Comment by EdwardJ1n** [comment]
Hi Marcos,

Please ignore it.
It is the Azure image version issue.

I choose the latest version of RHEL 8.1, it turns out to be RHEL 8.3..

I specify the older version, and it works.

Thanks.

Best Regards
Edward

On 17 Nov 2020, at 8:02 PM, Marcos Entenza <notifications@github.com<mailto:notifications@github.com>> wrote:


It does exist already @EdwardJ1n<https://github.com/EdwardJ1n>

https://github.com/redhat-sap/sap-rhsm/blob/master/tasks/manage-subs.yml#L50-L53
